services:
    jupyter:
        build:
            dockerfile:Dockerfile
        volumes:
            - ./jupyterdata:/home/jovyan/
        ports:
            - 9999:9998
        links:
            - db:database
        networks:
            - jupyter-network
    db:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - 5432:6432
        networks:
            - jupyter-network

networks:
    jupyter-network:
        name: jupyter-network
        driver: bridge
        attachable: true
